server:
  port: 7003
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureak7001.com:7001/eureka/,http://eureak7002.com:7002/eureka/
  instance:
    hostname: eureak7003.com